import './globals.css'
import type {Metadata} from 'next'
import {Rubik} from 'next/font/google'

//components
import Navbar from "@/app/components/Navbar";
import { NextFont } from "next/dist/compiled/@next/font";

const rubik: NextFont = Rubik({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={rubik.className}>
        <Navbar/>
        {children}
        </body>
        </html>
    )
}
